### PR TITLE
Fix special queries in dataview queries

### LINKED ISSUE #233: [BUG] Queries no longer working
**Describe the bug**
Upon upgrade from 1.8.2 to 2.0.1, all of my query tables are broken. Manually reverting sometimes fixes the problem, but I think something is wonky because it doesn't always fix the issue.

I think it has something to do with the string processing of the YAML within the db-folder configuration. All of my queries have double quotes and they all break. Previous versions of `db-folder` didn't put double quotes in the configuration. See the image 

**Error**
image

**Quotes in Config File
image

**To Reproduce**

All of the queries continue to work when used with standard dataview blocks.

**Queries that reproduce the error**
1. `from "/" where contains(tags, "Framework")`
2. `from "Operations/Calendar/Daily" where all(contains(tags, "Meeting"),(file.ctime >= date(today) - dur(30 day)), !Ignore)`

**Desktop (please complete the following information):**
 - OS: Mac OS 12.5

### PR DESCRIPTION
**Pull request by jcdeichmann**
Fixes #233 

## The Problem
Dataview queries were recently added as a database source. The query is stored in the database markdown file as a key value pair where the value is a string enclosed in double quotes. Dataview queries use double quotes  (`"`) when specifying folders, and was causing issues when saving to the markdown file since they weren't escaped. Additionally, newlines (`\n`) mess up the database markdown file since new key/values are expected on each line.

##  The Solution
To fix this, I've modified the  `UnmarshallConfigHandler` to escape double quotes and new lines on save, and the `MarshallConfigHandler` to unescape them when repopulating the settings from the markdown file. 

The below query has double quotes (`"`) and a new line (`\n`)
image

Here's the query successfully working
image

Here's the escaped query in the markdown file
image

This PR is ready for review, @RafaelGB

### CODE REVIEW

File: src/parsers/handlers/marshall/MarshallConfigHandler.ts [hunk 1]
```diff
@@ -31,7 +32,11 @@ export class MarshallConfigHandler extends AbstractYamlHandler {
     }
 
     loadDefaultConfig<K extends keyof LocalSettings>(key: K, value: Literal, localSettings: LocalSettings): LocalSettings {
-        localSettings[key] = value as any;
+        var escapedValue = value
+        if (typeof value === "string") {
```
Comment (RafaelGB) [inline src/parsers/handlers/marshall/MarshallConfigHandler.ts:36]: Dataview has a WrappedLiteral where you can obtain the type. This should work too, but could be interesting to use it
(examples in dataviewService.ts)

**Review by RafaelGB — APPROVED** [review]
Looks nice for me. Thanks for your contribution!

**Comment by jcdeichmann** [comment]
> Looks nice for me. Thanks for your contribution!

Shoot -- I just tested a couple more things and realized I was testing a previous build. There's a couple bugs in this. I'll investigate and update in a bit -- sorry about that!

**Comment by RafaelGB** [comment]
no rush, I just add a comment with the WrappedLiteral.

There are no conflict with the migration of the dispatcher

File: src/parsers/handlers/marshall/MarshallConfigHandler.ts (hunk 1 above)
Comment (RafaelGB) [reply src/parsers/handlers/marshall/MarshallConfigHandler.ts:36]: also. Could you use `let`instead of `var`? rollup build optimisation

File: src/helpers/QueryHelper.ts [hunk 2]
```diff
@@ -4,5 +4,5 @@ import { DatabaseCore } from "helpers/Constants";
 export function generateDataviewTableQuery(columns: Record<string, DatabaseColumn>, fromQuery: string): string {
     return `TABLE ${Object.keys(columns)
         .filter((key) => !key.startsWith("__") && !key.endsWith("__"))
-        .join(",")},${DatabaseCore.DATAVIEW_FILE},${DatabaseCore.FRONTMATTER_KEY} ${fromQuery.replace(/['"]+/g, '')}`
+        .join(",")},${DatabaseCore.DATAVIEW_FILE},${DatabaseCore.FRONTMATTER_KEY} ${fromQuery}`
```
Comment (jcdeichmann) [inline src/helpers/QueryHelper.ts:7]: For the new escaping to work, we have to stop stripping out the quotes and double quotes

Comment (RafaelGB) [reply src/helpers/QueryHelper.ts:7]: Let me know when you think its ready to merge

**Comment by RafaelGB** [comment]
I will merge it before generate conflicts with another branch

**Comment by jcdeichmann** [comment]
> I will merge it before generate conflicts with another branch

Sorry -- I was at work and wasn't able to respond and address your comments before you merged this. I opened another PR addressing those comments: https://github.com/RafaelGB/obsidian-db-folder/pull/237

**Comment by RafaelGB** [comment]
Oh thank you so much.

Sorry me merging it before your confirmation. I was absorbed with the big changes of the dispatcher and I wanted to make sure I didn't break your changes before I got my hands on the marshalls.
